services:
  famsub_api:
    image: ghcr.io/donfreddy/famsub-api:${IMAGE_VERSION:-latest}
    container_name: famsub_api
    restart: unless-stopped
    env_file: stack.env # This is used to load environment variables in the portainer
    ports:
      # This maps port from .env on the host to the same port number on the container.
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
    networks:
      - proxy

networks:
  proxy:
    external: true